


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


ALTER FUNCTION "public"."rls_auto_enable"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Activity" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "opp_id" bigint,
    "contact_id" bigint,
    "activity_type" "text",
    "activity_date" "date",
    "summary" "text",
    "details" "text"
);


ALTER TABLE "public"."Activity" OWNER TO "postgres";


ALTER TABLE "public"."Activity" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Activity_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Channel" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "type" "text",
    "notes" "text"
);


ALTER TABLE "public"."Channel" OWNER TO "postgres";


ALTER TABLE "public"."Channel" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Channel_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Contact" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "org_id" bigint,
    "name" "text",
    "designation" "text",
    "email" "text",
    "phone" "text",
    "linkedin_url" "text",
    "notes" "text"
);


ALTER TABLE "public"."Contact" OWNER TO "postgres";


ALTER TABLE "public"."Contact" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Contact_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Engagement" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "opp_id" bigint,
    "proposal_id" bigint,
    "title" "text",
    "start_date" "date",
    "expected_end_date" "date",
    "actual_end_date" "date",
    "status" "text",
    "delivery_status" "text",
    "actual_value" bigint,
    "notes" "text",
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."Engagement" OWNER TO "postgres";


ALTER TABLE "public"."Engagement" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Engagement_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Expense" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "expense_date" "date",
    "category" "text",
    "vendor" "text",
    "amount" double precision,
    "notes" "text"
);


ALTER TABLE "public"."Expense" OWNER TO "postgres";


ALTER TABLE "public"."Expense" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Expense_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Invoice" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "proposal_id" bigint,
    "engagement_id" bigint,
    "invoice_no" bigint,
    "invoice_date" "date",
    "due_date" "date",
    "subtotal" bigint,
    "tax_percent" real,
    "tax_amount" double precision,
    "discount" double precision,
    "total_amount" double precision,
    "amount_paid" double precision,
    "balance_due" double precision,
    "status" "text",
    "terms" "text",
    "notes" "text",
    "invoice_document" "text",
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."Invoice" OWNER TO "postgres";


ALTER TABLE "public"."Invoice" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Invoice_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Opportunity" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "org_id" bigint,
    "channel_id" bigint,
    "title" "text",
    "stage" "text",
    "status" "text",
    "expected_value" bigint,
    "probability" smallint,
    "opened_date" "date",
    "expected_close_date" "date",
    "notes" "text"
);


ALTER TABLE "public"."Opportunity" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."OpportunityContact" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "opp_id" bigint,
    "contact_id" bigint,
    "role" "text"
);


ALTER TABLE "public"."OpportunityContact" OWNER TO "postgres";


ALTER TABLE "public"."OpportunityContact" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."OpportunityContact_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."Opportunity" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Opportunity_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Organization" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "website" "text",
    "industry" "text",
    "notes" "text"
);


ALTER TABLE "public"."Organization" OWNER TO "postgres";


ALTER TABLE "public"."Organization" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Organization_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Payment" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "invoice_id" bigint,
    "payment_date" "date",
    "amount" double precision,
    "mode" "text",
    "reference_number" "text",
    "bank_txn_id" "text",
    "notes" "text",
    "updated_at" "date"
);


ALTER TABLE "public"."Payment" OWNER TO "postgres";


ALTER TABLE "public"."Payment" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Payment_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Proposal" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "opp_id" bigint,
    "version" integer,
    "amount" bigint,
    "sent_date" "date",
    "status" "text",
    "notes" "text",
    "title" "text",
    "scope" "text",
    "commercial_type" "text",
    "proposed_amount" bigint,
    "currency" "text",
    "start_date" "date",
    "end_date" "date",
    "valid_until" "date",
    "proposal_document" "text",
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."Proposal" OWNER TO "postgres";


ALTER TABLE "public"."Proposal" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Proposal_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Task" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "opp_id" bigint,
    "assigned_to" "text",
    "title" "text",
    "due_date" "date",
    "status" "text",
    "notes" "text"
);


ALTER TABLE "public"."Task" OWNER TO "postgres";


ALTER TABLE "public"."Task" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Task_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Activity"
    ADD CONSTRAINT "Activity_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Channel"
    ADD CONSTRAINT "Channel_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Contact"
    ADD CONSTRAINT "Contact_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Engagement"
    ADD CONSTRAINT "Engagement_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Expense"
    ADD CONSTRAINT "Expense_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Invoice"
    ADD CONSTRAINT "Invoice_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."OpportunityContact"
    ADD CONSTRAINT "OpportunityContact_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Opportunity"
    ADD CONSTRAINT "Opportunity_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Organization"
    ADD CONSTRAINT "Organization_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Payment"
    ADD CONSTRAINT "Payment_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Proposal"
    ADD CONSTRAINT "Proposal_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Task"
    ADD CONSTRAINT "Task_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Activity"
    ADD CONSTRAINT "Activity_contact_id_fkey" FOREIGN KEY ("contact_id") REFERENCES "public"."Contact"("id");



ALTER TABLE ONLY "public"."Activity"
    ADD CONSTRAINT "Activity_opp_id_fkey" FOREIGN KEY ("opp_id") REFERENCES "public"."Opportunity"("id");



ALTER TABLE ONLY "public"."Contact"
    ADD CONSTRAINT "Contact_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."Organization"("id");



ALTER TABLE ONLY "public"."Engagement"
    ADD CONSTRAINT "Engagement_opp_id_fkey" FOREIGN KEY ("opp_id") REFERENCES "public"."Opportunity"("id");



ALTER TABLE ONLY "public"."Engagement"
    ADD CONSTRAINT "Engagement_proposal_id_fkey" FOREIGN KEY ("proposal_id") REFERENCES "public"."Proposal"("id");



ALTER TABLE ONLY "public"."OpportunityContact"
    ADD CONSTRAINT "OpportunityContact_contact_id_fkey" FOREIGN KEY ("contact_id") REFERENCES "public"."Contact"("id");



ALTER TABLE ONLY "public"."OpportunityContact"
    ADD CONSTRAINT "OpportunityContact_opp_id_fkey" FOREIGN KEY ("opp_id") REFERENCES "public"."Opportunity"("id");



ALTER TABLE ONLY "public"."Opportunity"
    ADD CONSTRAINT "Opportunity_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "public"."Channel"("id");



ALTER TABLE ONLY "public"."Opportunity"
    ADD CONSTRAINT "Opportunity_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."Organization"("id");



ALTER TABLE ONLY "public"."Payment"
    ADD CONSTRAINT "Payment_invoice_id_fkey" FOREIGN KEY ("invoice_id") REFERENCES "public"."Invoice"("id");



ALTER TABLE ONLY "public"."Proposal"
    ADD CONSTRAINT "Proposal_opp_id_fkey" FOREIGN KEY ("opp_id") REFERENCES "public"."Opportunity"("id");



ALTER TABLE ONLY "public"."Task"
    ADD CONSTRAINT "Task_opp_id_fkey" FOREIGN KEY ("opp_id") REFERENCES "public"."Opportunity"("id");



ALTER TABLE "public"."Activity" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Channel" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Contact" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable read access for all users" ON "public"."Contact" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."Organization" FOR SELECT USING (true);



ALTER TABLE "public"."Engagement" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Expense" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Invoice" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Opportunity" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."OpportunityContact" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Organization" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Payment" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Proposal" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Task" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "anon";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "service_role";


















GRANT ALL ON TABLE "public"."Activity" TO "anon";
GRANT ALL ON TABLE "public"."Activity" TO "authenticated";
GRANT ALL ON TABLE "public"."Activity" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Activity_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Activity_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Activity_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Channel" TO "anon";
GRANT ALL ON TABLE "public"."Channel" TO "authenticated";
GRANT ALL ON TABLE "public"."Channel" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Channel_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Channel_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Channel_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Contact" TO "anon";
GRANT ALL ON TABLE "public"."Contact" TO "authenticated";
GRANT ALL ON TABLE "public"."Contact" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Contact_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Contact_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Contact_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Engagement" TO "anon";
GRANT ALL ON TABLE "public"."Engagement" TO "authenticated";
GRANT ALL ON TABLE "public"."Engagement" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Engagement_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Engagement_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Engagement_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Expense" TO "anon";
GRANT ALL ON TABLE "public"."Expense" TO "authenticated";
GRANT ALL ON TABLE "public"."Expense" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Expense_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Expense_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Expense_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Invoice" TO "anon";
GRANT ALL ON TABLE "public"."Invoice" TO "authenticated";
GRANT ALL ON TABLE "public"."Invoice" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Invoice_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Invoice_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Invoice_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Opportunity" TO "anon";
GRANT ALL ON TABLE "public"."Opportunity" TO "authenticated";
GRANT ALL ON TABLE "public"."Opportunity" TO "service_role";



GRANT ALL ON TABLE "public"."OpportunityContact" TO "anon";
GRANT ALL ON TABLE "public"."OpportunityContact" TO "authenticated";
GRANT ALL ON TABLE "public"."OpportunityContact" TO "service_role";



GRANT ALL ON SEQUENCE "public"."OpportunityContact_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."OpportunityContact_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."OpportunityContact_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Opportunity_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Opportunity_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Opportunity_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Organization" TO "anon";
GRANT ALL ON TABLE "public"."Organization" TO "authenticated";
GRANT ALL ON TABLE "public"."Organization" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Organization_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Organization_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Organization_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Payment" TO "anon";
GRANT ALL ON TABLE "public"."Payment" TO "authenticated";
GRANT ALL ON TABLE "public"."Payment" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Payment_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Payment_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Payment_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Proposal" TO "anon";
GRANT ALL ON TABLE "public"."Proposal" TO "authenticated";
GRANT ALL ON TABLE "public"."Proposal" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Proposal_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Proposal_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Proposal_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Task" TO "anon";
GRANT ALL ON TABLE "public"."Task" TO "authenticated";
GRANT ALL ON TABLE "public"."Task" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Task_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Task_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Task_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";



































